-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 11:11:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema datawarehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `datawarehouse` ;

-- -----------------------------------------------------
-- Schema datawarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datawarehouse` DEFAULT CHARACTER SET utf8 ;
USE `datawarehouse` ;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_cor_cutis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_cor_cutis` (
  `id_dim_cor_cutis` INT NULL AUTO_INCREMENT,
  `cod_cor_cutis` INT NULL,
  `cor_cutis` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_cor_cutis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_escola` (
  `id_dim_escola` INT NULL AUTO_INCREMENT,
  `cod_entidade` INT NULL,
  `nome` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_escola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_zona` (
  `id_dim_zona` INT NULL AUTO_INCREMENT,
  `cod_zona` INT NULL,
  `tipo_zona` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_Localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_Localizacao` (
  `id_dim_Localizacao` INT NULL AUTO_INCREMENT,
  `cod_Localizacao` INT NULL,
  `nome_municipio` TEXT NULL,
  `LATITUDE` VARCHAR(500) NULL,
  `LONGITUDE` VARCHAR(500) NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_Localizacao`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_Populacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_Populacional` (
  `id_dim_Populacional` INT NULL AUTO_INCREMENT,
  `cod_populacional` INT NULL,
  `LABEL` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_Populacional`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_ocorrencia` (
  `id_dim_ocorrencia` INT NULL AUTO_INCREMENT,
  `cod_rubrica` INT NULL,
  `rubrica` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_ocorrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_tempo` (
  `id_dim_tempo` INT NULL AUTO_INCREMENT,
  `cod_ID_TEMPO` INT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  `DIA_MES` INT NULL,
  `MES_NUMERO` INT NULL,
  `MES_NOME` VARCHAR(20) NULL,
  `DIA_SEMANA_NUMERO` INT NULL,
  `DIA_SEMANA_NOME` VARCHAR(20) NULL,
  `SEMANA_ANO` INT NULL,
  `DIA_ANO` INT NULL,
  `ANO` INT NULL,
  `HORA` INT NULL,
  `MINUTOS` INT NULL,
  `SEGUNDOS` INT NULL,
  `HORA_COMPLETA` TIME NULL,
  `PERIODO` VARCHAR(50) NULL,
  `TRIMESTRE_NUMERO` INT NULL,
  `TRIMESTRE_NOME` VARCHAR(20) NULL,
  `SEMESTRE_NUMERO` INT NULL,
  `SEMESTRE_NOME` VARCHAR(20) NULL,
  `DATA_BR` VARCHAR(20) NULL,
  `TIMESTAMP` DATETIME NULL,
  PRIMARY KEY (`id_dim_tempo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_periodo`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_periodo` (
  `id_dim_periodo` INT NULL AUTO_INCREMENT,
  `cod_periodo` INT NULL,
  `periodo` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_periodo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_sexo` (
  `id_dim_sexo` INT NULL AUTO_INCREMENT,
  `cod_sexo` INT NULL,
  `sexo_pessoa` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_quadra` (
  `id_dim_quadra` INT NULL AUTO_INCREMENT,
  `cod_quadra` INT NULL,
  `quadra` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_quadra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`dim_dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`dim_dependencia` (
  `id_dim_dependencia` INT NULL AUTO_INCREMENT,
  `cod_dependencia` INT NULL,
  `dependencia` TEXT NULL,
  `version` INT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id_dim_dependencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`fato_crime_area_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datawarehouse`.`fato_crime_area_escola` (
  `total_crime` FLOAT NULL,
  `porcentagem_crime` FLOAT NULL,
  `dim_escola_id_dim_escola` INT NOT NULL,
  `dim_sexo_id_dim_sexo` INT NOT NULL,
  `dim_quadra_id_dim_quadra` INT NOT NULL,
  `dim_tempo_id_dim_tempo` INT NOT NULL,
  `dim_periodo_id_dim_periodo` INT NOT NULL,
  `dim_dependencia_id_dim_dependencia` INT NOT NULL,
  `dim_ocorrencia_id_dim_ocorrencia` INT NOT NULL,
  `dim_Localizacao_id_dim_Localizacao` INT NOT NULL,
  `dim_Populacional_id_dim_Populacional` INT NOT NULL,
  `dim_zona_id_dim_zona` INT NOT NULL,
  `dim_cor_cutis_id_dim_cor_cutis` INT NOT NULL,
  PRIMARY KEY ( `dim_escola_id_dim_escola`, `dim_sexo_id_dim_sexo`, `dim_quadra_id_dim_quadra`, `dim_tempo_id_dim_tempo`, `dim_periodo_id_dim_periodo`, `dim_dependencia_id_dim_dependencia`, `dim_ocorrencia_id_dim_ocorrencia`, `dim_Localizacao_id_dim_Localizacao`, `dim_Populacional_id_dim_Populacional`,  `dim_zona_id_dim_zona`, `dim_cor_cutis_id_dim_cor_cutis`),
  -- INDEX `fk_fato_crime_area_escola_dim_escola1_idx` (`dim_escola_id_dim_escola` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_sexo1_idx` (`dim_sexo_id_dim_sexo` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_quadra1_idx` (`dim_quadra_id_dim_quadra` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_id_dim_tempo1_idx` (`dim_tempo_id_dim_tempo` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_conduta_copy31_idx` (`dim_periodo_id_dim_periodo` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_dependencia1_idx` (`dim_dependencia_id_dim_dependencia` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_ocorrencia1_idx` (`dim_ocorrencia_id_dim_ocorrencia` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_municipio1_idx` (`dim_Localizacao_id_dim_Localizacao` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_zona1_idx` (`dim_zona_id_dim_zona` ASC) VISIBLE,
  -- INDEX `fk_fato_crime_area_escola_dim_cor_cutis1_idx` (`dim_cor_cutis_id_dim_cor_cutis` ASC) VISIBLE,
  CONSTRAINT `fk_fato_crime_area_escola_dim_escola1`
    FOREIGN KEY (`dim_escola_id_dim_escola`)
    REFERENCES `datawarehouse`.`dim_escola` (`id_dim_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_sexo1`
    FOREIGN KEY (`dim_sexo_id_dim_sexo`)
    REFERENCES `datawarehouse`.`dim_sexo` (`id_dim_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_quadra1`
    FOREIGN KEY (`dim_quadra_id_dim_quadra`)
    REFERENCES `datawarehouse`.`dim_quadra` (`id_dim_quadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_id_dim_tempo1`
    FOREIGN KEY (`dim_tempo_id_dim_tempo`)
    REFERENCES `datawarehouse`.`dim_tempo` (`id_dim_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_periodo`
    FOREIGN KEY (`dim_periodo_id_dim_periodo`)
    REFERENCES `datawarehouse`.`dim_periodo` (`id_dim_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_dependencia1`
    FOREIGN KEY (`dim_dependencia_id_dim_dependencia`)
    REFERENCES `datawarehouse`.`dim_dependencia` (`id_dim_dependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_ocorrencia1`
    FOREIGN KEY (`dim_ocorrencia_id_dim_ocorrencia`)
    REFERENCES `datawarehouse`.`dim_ocorrencia` (`id_dim_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_Populacional`
    FOREIGN KEY (`dim_Populacional_id_dim_Populacional`)
    REFERENCES `datawarehouse`.`dim_Populacional` (`id_dim_Populacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_Localizacao1`
    FOREIGN KEY (`dim_Localizacao_id_dim_Localizacao`)
    REFERENCES `datawarehouse`.`dim_municipio` (`id_dim_Localizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_zona1`
    FOREIGN KEY (`dim_zona_id_dim_zona`)
    REFERENCES `datawarehouse`.`dim_zona` (`id_dim_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_crime_area_escola_dim_cor_cutis1`
    FOREIGN KEY (`dim_cor_cutis_id_dim_cor_cutis`)
    REFERENCES `datawarehouse`.`dim_cor_cutis` (`id_dim_cor_cutis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
